frontend/src/pages/MiniGameReadyPage/MiniGameReadyPage.styled.ts, frontend/src/pages/MiniGameReadyPage/MiniGameReadyPage.tsx
- close #93 
1. 미니 게임 대기 화면 UI를 구현했습니다.
2. 각 게임 사이의 대기 시간은 3초로 설정했습니다. 3초가 지나면 게임 시작 화면으로 이동하며, url을 `/room/1/2/ready` -> `/room/1/2/play`로 넘어가도록 구현했습니다.
페이지 가장 바깥쪽에 공통 컴포넌트인 `Layout`을 적용해서 구현해봤는데, 의도대로 사용된 건지 확인부탁드립니다.
지금 `Description` 태그로 `게임이 시작될 때까지 조금만 기다려주세요`라는 텍스트를 넣어놨는데, `line-height` 속성이 없어서 텍스트 사이의 줄 높이가 붙어있는 느낌이 들었습니다. 전체적으로 `line-height`를 피그마 기반으로 설정하는건 어떻게 생각하시나용 ?..?
=> [feat] MiniGameReadyPage 구현

frontend/src/features/miniGame/cardGame/components/CircularProgress/CircularProgress.stories.tsx, frontend/src/features/miniGame/cardGame/components/CircularProgress/CircularProgress.tsx
- close #131 
예시로 타이머를 10초로 맞춰놓고 테스트를 진행했는데, 시작할 때 10초에서 바로 9초로 바뀐 상태로 진행되는 문제가 있었습니다.
아래 영상을 보면 알 수 있는데, 리셋 버튼을 눌렀을 때 1초동안 10이 화면에 띄워진 상태에서 진행바가 움직이지 않는 모습을 볼 수 있습니다.
그리고 마지막에 0으로 표시된 상태일 때도 1초가 지난 후에 진행바가 꽉 채워지게 됩니다.
그렇기 때문에 실질적으로는 **11초가 세어지는 것**이었습니다.
https://github.com/user-attachments/assets/dcfc4f2c-4bc9-40aa-b88c-3f30a64da115
아래는 구글 타이머인데요, 보통은 10초부터 카운트가 들어가야 합니다. 그래서 끝날 때 1초로 표시된 상태로 1초가 지나면 0이 되고 타이머가 종료됩니다. 하지만, 제가 구현한 타이머에서는 화면에 0으로 표시된 상태에서 1초가 지나고 종료가 됩니다.
https://github.com/user-attachments/assets/a4fd6734-eb96-4753-bbf9-7fa6658e2242
게임 타이머의 경우에는 사용자 입장에서 게임을 진행할 때 매우 예민한 부분이고 중요하다고 판단하여 수정하기로 했습니다.
문제 원인 분석 전에 코드 이해를 돕기 위해서 각각의 변수가 어떤 역할을 하는지 요약해둘게요!
- `current`: 현재 남은 시간
- `total`: 전체 타이머 시간
- `progress`: 진행률 (0~1 사잇값)
- `radius`: 반지름 (고정 상수)
- `circumference`: 원의 둘레 (고정 …
=> [feat] CircularProgress 타이머 이슈

frontend/public/index.html, frontend/src/styles/global.css
- close #148 
모바일 테스트 시 UX 문제있는 부분들을 해결하기 위해 모바일 터치 효과들을 제거해두었습니다.
테스트해보고 불편사항 있으면 추가 이슈 부탁드려요!
* `overflow-x: hidden`
→ 가로 스크롤 방지 (콘텐츠 튐 방지)
* `position: fixed`, `width: 100%`, `height: 100%`
→ 모바일 환경에서 전체 뷰포트를 고정하여 레이아웃 안정화
* `-webkit-user-scalable: no`, `-moz-user-scalable: no`, `-ms-user-scalable: no`
→ 사용자의 핀치 줌(확대/축소) 비활성화
* `touch-action: manipulation`
→ 터치 시 더블탭 확대 및 브라우저 기본 동작 방지
---
* `-webkit-text-size-adjust: 100%`, `-ms-text-size-adjust: 100%`, `text-size-adjust: 100%`
→ 텍스트 자동 확대 방지
* `touch-action: manipulation`
→ 터치 관련 기본 브라우저 동작 제거 (이중 탭 확대 등)
* `-webkit-tap-highlight-color: transparent`
→ 터치 시 파란 하이라이트 제거
* `-webkit-touch-callout: none`
→ 길게 누를 때 나오는 시스템 메뉴 비활성화
* `-webkit-user-select`, `-moz-user-select`, `-ms-user-select`, `user-select: none`
→ 텍스트 선택 비활성화
---
* …
=> [feat] 모바일 터치 효과 제거

frontend/src/pages/MiniGameResultPage/MiniGameResultPage.styled.ts
- close #173 
- 주문 리스트 페이지에서 스크롤이 되도록 아래 `css` 속성을 추가했습니다.
```css
height: 100%;
overflow: scroll;
&::-webkit-scrollbar {
display: none;
}
```
중점사항
=> [fix] 주문 리스트 페이지 스크롤 안됨

frontend/src/assets/close-icon.svg, frontend/src/assets/close.svg, frontend/src/components/@common/CloseIcon/CloseIcon.tsx, frontend/src/components/@common/Input/Input.styled.ts, frontend/src/components/@common/Input/Input.tsx, frontend/src/components/@common/Modal/ModalHeader/ModalHeader.styled.ts, frontend/src/components/@common/Modal/ModalHeader/ModalHeader.tsx, frontend/src/layouts/Layout.stories.tsx, frontend/src/styles/emotion.d.ts
- close #147 
ModalHeader와 Input에 있는 Close(X) 버튼 아이콘이 stroke(색상)과 strokeWidth(두께)을 제외하고 동일한 속성을 가지고 있어서 통합해주었습니다.
이때 동적 스타일링을 위해 tsx 로 만들어 Props로 자유롭게 스타일링 조정 가능하도록 해주었습니다.
기존에는 Input 부분의 strokeWidth가 1.3, ModalHeader 부분의 strokeWidth가 2였는데요, 사실상 2로 통합해도 UI상 큰 문제는 없고 훨씬 또렷하게 화면에 나타나는 것 같다고 느껴서 2로 통일해주었습니다. 사실상 기존과 큰 차이는 없어요!
아이콘 tsx 파일을 어느 위치에 둘까 고민하다가, 우선 `components/common` 하위에 CloseIcon으로 두었습니다.
실질적으로 SVG를 tsx 코드로 인라인(import) 관리하는 경우가 많아진다면 Icon 폴더를 하나 더 감싸줄 생각이었는데, 저희 프로젝트에서는 동적 스타일링이 필요한 SVG가 해당 아이콘을 제외하고는 거의 존재하지 않는 것 같아서 우선은 지금 그대로 두었어요!
SVG를 전부 tsx 로 관리할지 아니면 지금처럼 assets에 보관하여 s3 버킷에 올려둘지 고민을 했는데요.
결론적으로는, **동적 스타일링이 필요한 부분은 전자, 단순 정적 파일인 경우에는 assets로 관리**하고자 합니다.
그 이유는 간단하게 말하자면 다음과 같은데요,
**tsx로 관리**
- 장점: 동적 스타일링 유용, 애니메이션이나 인터랙션 쉽게 가능, 즉시 렌더링(별도 네트워크 요청 필요 X)
- 단점: 브라우저 캐싱 불가, …
=> [refactor] Input 및 Modal의 X 버튼 아이콘 일원화

frontend/src/apis/websocket/contexts/WebSocketProvider.tsx
- close #276 
응답 타입 지정을 성공/에러를 나눠서 적용했습니다. 
```js
type WebSocketSuccess<T> = {
success: true;
data: T;
errorMessage: null;
};
type WebSocketError = {
success: false;
data: null;
errorMessage: string;
};
```
isSuccess가 false일때 에러 던지는 로직 추가 
```js
const parsedMessage = JSON.parse(message.body) as WebSocketMessage<T>;
const isSuccess = parsedMessage.success;
if (!isSuccess) {
throw new Error(parsedMessage.errorMessage);
}
const data = parsedMessage.data as T;
```
중점사항
=> [refactor] WebSocket의 Data파싱과 에러 처리 추가 

backend/src/main/java/coffeeshout/room/application/RoomService.java, backend/src/main/java/coffeeshout/room/domain/Room.java, backend/src/main/java/coffeeshout/room/ui/RoomWebSocketController.java, backend/src/main/java/coffeeshout/room/ui/request/MiniGameSelectMessage.java, backend/src/test/java/coffeeshout/room/application/RoomServiceTest.java, backend/src/test/java/coffeeshout/room/ui/RoomWebSocketControllerTest.java
- close #296 
- select/unselectMiniGame 메서드 제거 및 updateMiniGames 메서드 도입
- Room 객체의 미니게임 초기화 메서드(clearMiniGames) 추가
- MiniGameSelectMessage의 miniGameType 필드를 miniGameTypes(List)로 변경
- WebSocket 요청 URL을 update-minigames로 통합
- 관련 테스트 코드 수정 및 매핑 로직 반영
중점사항
=> [refactor] 미니게임 선택 시, 항상 리스트로 선택된 게임 서버로 전송

frontend/src/apis/websocket/contexts/WebSocketProvider.tsx, frontend/src/apis/websocket/hooks/useWebSocketSubscription.ts, frontend/src/features/room/lobby/components/MiniGameSection/MiniGameSection.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #297 
선택한 미니게임 상태를 MiniGameSection이 아니라 LobbyPage 에서 useState로 관리해서 Props로 내려주었습니다. 왜냐하면, 토글이 계속 이동해도 상태가 유지되기 위함입니다.
넘겨주는 과정에서 Props를 넘겨주기 위해 SECTIONS 객체를 외부에서 컴포넌트 내부로 옮겼습니다.
```tsx
const SECTIONS: SectionComponents = {
참가자: <ParticipantSection />,
룰렛: <RouletteSection />,
미니게임: (
<MiniGameSection
selectedMiniGames={selectedMiniGames}
handleMiniGameClick={handleMiniGameClick}
/>
),
};
```
`useWebSocketSubscription`에서 두 번째 인자로 들어가는 onData를 메모이제이션 해줘야하는데, 해당 훅 내부에서는 안되고, 그 외부에서 감싸서 넘겨줘야 하더라구요.. 왜 안에서 감쌌을때 안되는지 모르겠지만, 일단 외부에서 감싸서 메모이제이션 해줬습니다. 이러면 onData가 실제로 변경될 때만 재생성되게 하여, SEND 할 때 unsubscribe -> subscribe 이렇게 다시 재구독 되는 동작을 막아둘 수 있습니다. 
```tsx
const handleMiniGameData = useCallback((data: MiniGameResponse) => {
setSelectedMiniGames(data);
}, []); …
```
=> [feat] 미니 게임 선택 웹소켓 연동

frontend/src/features/entry/pages/EntryMenuPage/EntryMenuPage.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #301 
시작 버튼을 누르면 send가 보내지고 
```js
const handleClickGameStartButton = () => {
send(`/room/${joinCode}/minigame/command`, {
commandType: 'START_MINI_GAME',
commandRequest: {
hostName: myName,
},
});
};
```
메세지가 오면 game ready 페이지로 이동하도록 구현했습니다.
기존에 seletecedMinigames[0] 으로 설정되어있던 경로를 서버에서 받아온 MiniGameType 데이터로 변경했습니다 
```js
const handleGameStart = useCallback(
(data: { miniGameType: MiniGameType }) => {
const { miniGameType: nextMiniGame } = data;
navigate(`/room/${joinCode}/${nextMiniGame}/ready`);
},
[joinCode]
);
useWebSocketSubscription(`/room/${joinCode}/round`, handleGameStart);
```
중점사항
=> [feat] 미니게임 시작 웹소켓 연동 

.github/workflows/frontend-ci.yml, frontend/webpack.common.js
- close #286
배포 했을 때 환경변수를 문자열로 읽지 않아서 화면이 뜨지 않는 현상이 있습니다.
예상하기로는 `.env` 파일에 있는 환경변수를 문자열로 제대로 파싱하지 못해서 `process.env`를 직접 참조하고 있어서 문제가 발생하는 것 같았습니다.
1. .env 파일 경로가 혹시 프로젝트 루트에 있는 걸로 접근하는 게 문제인가 해서, 직접 path를 명확히 지정해주었어요. 저희는 /frontend/.env 에 존재하므로 현재 webpack 설정 파일과 같은 위치에 있는 .env에 접근할 수 있도록 했습니다. 되는지는 배포 해봐야 확인 가능할 것 같아요! https://github.com/woowacourse-teams/2025-coffee-shout/commit/9f44067cdeb1345705a55ab6aff2a24a417fd609
```ts
// `webpack.common.js`이 위치한 디렉터리의 절대 경로를 가리킴
{ path: path.resolve(__dirname, '.env') }
```
2. `.env` 파일이 잘 읽히는지, `DefinePlugin`이 제대로 동작하는지 확인해보고자 하여, CI 빌드 로그에 디버깅 코드 추가했습니다. 오류 수정되면 삭제할 예정입니다. https://github.com/woowacourse-teams/2025-coffee-shout/commit/02dfdeb873a92b05ef3714356c9649df7495b6a8
=> [fix] 배포 시 환경변수 오류

frontend/src/contexts/CardGame/CardGameContext.ts, frontend/src/contexts/CardGame/CardGameProvider.tsx, frontend/src/features/entry/pages/EntryMenuPage/EntryMenuPage.tsx, frontend/src/features/miniGame/cardGame/components/Round/Round.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx, frontend/src/features/miniGame/components/MiniGameTransition/MiniGameTransition.stories.tsx, frontend/src/features/miniGame/components/MiniGameTransition/MiniGameTransition.tsx, frontend/src/features/miniGame/pages/MiniGameReady/MiniGameReadyPage.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx, frontend/src/router.tsx, frontend/src/types/miniGame.ts, frontend/src/types/round.ts
- close #300 
- CardGameProvider를 만들어 게임 관련 구독과 상태를 여기서 처리했습니다. 
- 서버에서 내려주는 카드 게임 상태 (CardGameState, CardGameRound) 기반으로 클라이언트 변수를 추가했습니다. 
- 카드 렌더링을 실제 서버에서 내려주는 cardInfoMessages를 사용하여 렌더링 하도록 변경 했습니다. 
```js
export type CardGameState = 'READY' | 'LOADING' | 'PLAYING' | 'SCORE_BOARD' | 'DONE';
export type CardGameRound = 'FIRST' | 'SECOND'
```
READY는 서버에서만 가지고있는 상태여서 클라이언트쪽에는 오지 않습니다
SCORE_BOARD 상태는 카드가 다 선택되거나 10초가 지났을시 바로 화면이 넘어가는 것이 이상해서 1.5초 정도 완충역할로 넣은 상태라고 합니다~
```js
//1라운드 시작
const isFirstRoundPlaying = cardGameState === 'PLAYING' && currentRound === 'FIRST';
//2라운드로 가는 Transition 컴포넌트 나오는 시점
const isSecondRoundLoading = cardGameState === 'LOADING' && currentRound === 'SECOND';
//2라운드 시작
const isSecondRoundPlaying = cardGameState === 'PLAYING' && currentRound === 'SECOND';
//2라운드 …
```
=> [feat] 게임 상태 실시간 업데이트 웹소켓 연동 

frontend/src/features/miniGame/cardGame/components/Round/Round.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #292 
https://github.com/user-attachments/assets/805c28eb-e643-49b1-9f1f-f504b5818ee1
1. 카드를 선택하면 실시간으로 참여중인 플레이어에게 보여지도록 웹소켓을 연결했습니다.
2. 선택된 카드들을 보여주기 위해 `CardFront` 컴포넌트를 보여주는 조건에 현재 서버에서 받아온 `cardInfo`의 `selected` 필드가 `true`인지를 검사하는 로직을 추가했습니다.
```tsx
cardInfo.selected || selectedCardInfo[round].index === index ?
```
중점사항
=> [feat] 카드 선택 웹소켓 연동

frontend/src/features/miniGame/cardGame/components/Round/Round.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx, frontend/src/features/room/lobby/components/MenuModifyModal/MenuModifyModal.tsx, frontend/src/features/room/lobby/components/ParticipantSection/ParticipantSection.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #291 
1. 메뉴를 수정하는 웹소켓을 연결했습니다.
2. `LobbyPage`에서 이미 `/room/{joinCode}`에 대한 `Subscribe`를 처리한 상태였기 때문에, `MenuModifyModal`에서 `send` 요청을 보내는 로직만 추가해 주었습니다!
3. 본인이 아닌 다른 참가자의 아이콘에서는 메뉴 수정 모달이 클릭되지 않도록 핸들러를 제거했습니다.
아직 메뉴 아이콘을 넣지 않아서 시각적으로 테스트는 못하지만, `participants`를 출력해보면 메뉴 모달에서 메뉴를 변경한 이후에 변경된 내용을 확인할 수 있습니당
=> [feat] 메뉴 웹소켓 연동

frontend/src/apis/rest/apiRequest.ts, frontend/src/features/home/components/EnterRoomModal/EnterRoomModal.tsx
- close #256 
https://github.com/user-attachments/assets/94c9002a-6fd3-41af-832c-87c0c5c7fe7f
1. 참여코드 존재 여부 확인을 위한 `api`를 연동하고 예외 처리를 진행했습니다.
2. 사용자의 불편함을 줄이고자 `toUpperCase()`로 참여 코드를 소문자로 입력해도 대문자로 변환되도록 처리했습니다.
3. 현재 연결을 시도하는 `api` 응답값의 `contentType`이 `application/problem+json`으로 넘어와서 기존 `apiRequest`함수 내부에서 제대로 된 에러 메세지를 처리하지 못하는 문제가 있었습니다. 이를 해결하기 위해 `json`으로 파싱하는 조건문을 수정했습니다.
```javascript
if (contentType && (contentType.includes('application/json') || contentType.includes('application/problem+json'))) {
errorData = await response.json();
errorMessage = errorData.detail;
}
```
일단은 지금 사용자한테 보여주는 `errorMessage`를 `errorData.detail`의 값을 받아오는걸로 설정이 되어 있는데, 추후 에러 코드로 변환하는 작업이 필요할 것 같아서
이건 따로 이슈 파서 진행하겠습니다 ~
```javascript
errorData = await response.json();
errorMessage = errorData.detail; // …
```
=> [feat] 참여코드 존재여부 조회 API 기능 구현

frontend/src/contexts/CardGame/CardGameContext.ts, frontend/src/contexts/CardGame/CardGameProvider.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx, frontend/src/features/miniGame/pages/MiniGameResultPage/MiniGameResultPage.tsx, frontend/src/features/room/order/pages/OrderPage.tsx, frontend/src/features/room/roulette/pages/RoulettePlayPage/RoulettePlayPage.tsx, frontend/src/features/room/roulette/pages/RouletteResultPage/RouletteResultPage.tsx, frontend/src/types/miniGame.ts
- close #302
- 카드 게임 결과 및 랭킹 카드 웹소켓 연동
-  order 페이지에서 당첨자 연동
-  게스트 화면에서도 룰렛이 돌아가도록 설정
- 점수,랭킹은 정적 데이터라 rest api 로 변경하기로 했습니다! 일단 웹소켓으로 구현하였습니다. 
💬 리뷰 중점사항
중점사항
=> [feat] 카드 게임 결과 및 랭킹 카드 웹소켓 연동

backend/src/main/java/coffeeshout/global/exception/RestExceptionHandler.java, backend/src/main/java/coffeeshout/global/log/LogAspect.java, backend/src/main/java/coffeeshout/minigame/application/CardGameService.java, backend/src/main/java/coffeeshout/minigame/domain/cardgame/CardGame.java, backend/src/main/java/coffeeshout/minigame/ui/MiniGameRestController.java, backend/src/main/java/coffeeshout/minigame/ui/MiniGameWebSocketController.java, backend/src/main/java/coffeeshout/minigame/ui/response/MiniGameRanksResponse.java, backend/src/main/java/coffeeshout/minigame/ui/response/MiniGameScoresResponse.java, backend/src/main/java/coffeeshout/room/application/RoomService.java, backend/src/main/java/coffeeshout/room/domain/Playable.java, backend/src/main/java/coffeeshout/room/domain/Room.java, backend/src/main/java/coffeeshout/room/ui/RoomRestController.java, backend/src/main/java/coffeeshout/room/ui/response/MiniGameSelectedResponse.java, backend/src/main/resources/application.yml, backend/src/main/resources/logback-spring.xml, backend/src/test/java/coffeeshout/fixture/MiniGameDummy.java, backend/src/test/java/coffeeshout/minigame/domain/cardgame/CardGameTest.java, backend/src/test/java/coffeeshout/room/application/RoomServiceTest.java, backend/src/test/java/coffeeshout/room/domain/RoomTest.java
- close #335 
- close #336 
1. 카드게임 점수 및 등수 Rest API로 전환
2. 선택된 미니게임 목록 반환하는 Rest API 추가
3. 로그 콘솔 출력 형식 변경
4. 관련 테스트 작성
중점사항
=> [feat] 카드게임 점수 및 등수 Rest API로 전환

frontend/src/components/@common/Button/Button.styled.ts, frontend/src/features/room/lobby/components/GameReadyButton/GameReadyButton.tsx, frontend/src/features/room/lobby/components/GameStartButton/GameStartButton.tsx, frontend/src/features/room/lobby/components/HostWaitingButton/HostWaitingButton.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #343 
게임 준비 기능구현에 필요한 버튼들을 아래와 같이 컴포넌트로 분리하였습니다. 
`GameReadyButton` 컴포넌트
`GameStartButton` 컴포넌트
`HostWaitingButton` 컴포넌트
**분리한 이유:**
LobbyPage에서 조건부 렌더링을 통해 버튼을 표시해야 하는데, 공통 버튼 컴포넌트를 직접 사용하는 방식은 코드가 길어지고 가독성이 떨어진다고 생각해 분리하였습니다. 
또한 Host/Guest 뿐만 아니라 Ready 상태에 따라서도 버튼 렌더링이 달라져서 삼항연산자를 사용하면 가독성이 떨어진다고 느꼈습니다. 따라서 `renderGameButton` 라는 함수를 만들었습니다. 
- `GameReadyButton` 렌더링
- 플레이어의 준비 상태(isReady)에 따라 버튼 스타일 변경 
- 모든 참가자가 준비 완료(isAllReady)인 경우: `GameStartButton` 렌더링
- 일부 참가자가 준비되지 않은 경우: `HostWaitingButton` 렌더링
- 준비된 참가자 수와 전체 참가자 수 표시
`isReady`, `isAllready` 같은 값들은 이미 participants state에 있기때문에 또 useState로 상태를 만들면 중복 상태라고 생각했습니다. 그래서 해당 값들은 상태가 아닌 변수를 만들어서 처리했습니다. 
ui적으로 옆에있는 공유버튼과 loading 스타일 버튼이 같이 있으면 어색한데 어떻게 고쳐야 좋을지 잘 모르겠더라고요. 그래서 임시로 ready 스타일도 만들어봤는데 둘중 어떤 스타일이 더 좋은것 같나요? 
<p …
=> [feat] 게임준비 기능 추가 

frontend/src/components/@common/SelectBox/SelectBox.stories.tsx, frontend/src/components/@common/SelectBox/SelectBox.styled.ts, frontend/src/components/@common/SelectBox/SelectBox.tsx, frontend/src/components/@common/SelectBox/hooks/useClickOutside.ts, frontend/src/components/@common/SelectBox/hooks/useSelectBox.ts
- close #83
1. 기존에 쓰이지 않는 속성인 `disabled` 속성을 삭제했습니다.
2. 기존 select 컴포넌트의 관심사 분리를 위해 아래의 커스텀 훅으로 분리해주었습니다.
`useSelectBox`: `selectBox` 내부의 상태 관리 로직을 처리하는 커스텀 훅
`useClickOutside`: 외부 클릭을 감지하는 커스텀 훅
컴포넌트 내부에 `hooks` 폴더를 만들어 `SelectBox` 컴포넌트 안에 넣었는데, 생각해보니 훅의 성격에 따라 위치를 구분해야 할 것 같습니다.
`useSelectBox` 같은 경우는 해당 컴포넌트에만 특화된 로직이라 현재 위치가 적절하다고 생각하는데, `useClickOutside` 훅은 모달, 드롭다운, 툴팁 등 다른 컴포넌트에서도 재사용 가능할 것 같습니다.
이런 경우 `useClickOutside`는 전역 `hooks` 폴더로 옮기는 것이 더 나은 구조라고 생각하는데, 어떻게 생각하시나용 ?.?
=> [refactor] Selectbox 컴포넌트 리팩토링

frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx
- close #374 
수정 전 타이머 리셋 조건
```js
if (currentTime === 0 && currentRound === 2 && currentCardGameState === 'PLAYING')
```
**문제 발생 이유** 
카드를 다 클릭하고 넘어갔을 때는 currentTIme 이 0 이 아니여서 해당 조건을 만족하지 못했습니다. 
currentTIme===0 만 제거한 경우 2라운드 타이머가 게속 초기화되는 문제가 발생해서
useRef를 사용해서 타이머 초기화 상태를 저장해서 사용했습니다. 
수정 후 타이머 리셋 조건
```js
if (currentRound === 2 && currentCardGameState === 'PLAYING') {
if (!isTimerReset.current) {
setCurrentTime(TOTAL_COUNT);
isTimerReset.current = true;
}
}
```
수정 전 영상
https://github.com/user-attachments/assets/df1a4da2-b336-46cf-9907-28cc5ef7f5a5
수정 후 영상 
https://github.com/user-attachments/assets/5eca4700-4d2a-4d22-b715-83acc6cc299e
중점사항
=> [refactor] 다음 라운드로 넘어갈때 타이머 올바르게 초기화하기

frontend/src/features/room/order/pages/OrderPage.tsx
- close #386 
마지막 OrderPage에서 data를 받고 웹소켓 연결을 끊는 로직을 추가해 주었습니다. 
연결을 끊었을때 send를 보내지 않도록 아래와 같이 isConntectd를 확인하게 조건을 추가하였습니다! 
```js
useEffect(() => {
if (joinCode && isConnected) {
send(`/room/${joinCode}/update-players`);
}
}, [joinCode, send]);
```
1.
중점사항
=> [fix] 하나의 플로우가 끝날시 웹소켓 연결 안끊기는 문제 해결

frontend/src/main.tsx
DSN 키는 원래 의도적으로 공개되도록 설정되었더라구요.
배포 환경에서는 Sentry 에러가 안잡히는데, 개발 환경에서는 Sentry 에러가 잘 잡혀서 문제를 찾아보니,
환경변수 이슈인 것 같아서 우선 DSN 키 환경변수를 하드코딩 식으로 바꿔두었습니다.
[My DSN key is publicly visible, is this a security vulnerability?](https://sentry.zendesk.com/hc/en-us/articles/26741783759899-My-DSN-key-is-publicly-visible-is-this-a-security-vulnerability)
자료 출처는 @ExceptAnyone 입니다 :)
=> [fix] Sentry DSN 키를 환경 변수에서 하드코딩 값으로 변경

backend/src/main/java/coffeeshout/global/handler/CustomStompChannelInterceptor.java, backend/src/main/java/coffeeshout/global/interceptor/CustomStompChannelInterceptor.java, backend/src/main/java/coffeeshout/global/websocket/event/RoomStateUpdateEvent.java, backend/src/main/java/coffeeshout/global/websocket/event/RoomStateUpdateEventListener.java, backend/src/main/java/coffeeshout/room/application/RoomService.java, backend/src/main/java/coffeeshout/room/domain/Room.java, backend/src/main/java/coffeeshout/room/domain/player/Players.java, backend/src/main/java/coffeeshout/room/domain/roulette/Roulette.java, backend/src/test/java/coffeeshout/minigame/ui/CardGameIntegrationTest.java
- close #454
- `CustomStompChannelInterceptor`에서 WebSocket 연결 해제, 에러 및 실패 시 플레이어 제거 로직 추가
- `handlePlayerDisconnection` 메서드로 게임 진행 중 연결 해제 시 복구 절차 구현
- 세션 및 플레이어 매핑 관리 로직 개선 (`playerSessionMap`, `sessionPlayerMap`)
- `RoomService`에 플레이어 제거 메서드(`removePlayer`) 추가
- 룰렛에서 플레이어 제거 시 확률 리밸런싱 로직 구현
- `Players` 및 `Roulette` 클래스에 플레이어 삭제 기능 추가
중점사항
=> [feat] 앱 전환 시 웹소켓 재연결 및 해제 로직 추가

backend/src/main/java/coffeeshout/global/interceptor/CustomStompChannelInterceptor.java
- close #이슈번호
1. 세션 관리하는 곳에서 menuId 제거
중점사항
=> [fix] 플레이어-세션 매핑 키에서 `menuId` 제거 및 연결 해제 로직 수정

frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #402 
1. 참여자가 나 혼자이거나 미니게임이 선택된게 없을 경우, `alert`를 띄우도록 했습니다.
중점사항
=> [feat] 미니게임 선택 안하면 게임을 시작하지 못하도록 하기

frontend/src/contexts/CardGame/CardGameProvider.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx
- close #495 
- 카드 클릭 시 setSelectedCardInfo 호출로 상태가 변경되어 재렌더링 발생.
- 현재 웹소켓 구독/해제 로직이 useEffect에서 마운트/언마운트 시점에 실행되는데, 재렌더링 시 언마운트 → 구독 해제 발생.
- 하필 이 구독 해제 타이밍에 서버에서 메시지가 도착해 클라이언트가 수신하지 못함.
- setSelectedCardInfo를 Provider로 올려놨지만, 여전히 하위 컴포넌트에서 이를 호출하는 방식을 유지한 것이 원인으로 보임.
- setSelectedCardInfo를 아예 서버에서 내려주는 메세지에서 내 카드를 추출해서 하는 방식으로 변경
- cardGameProvider만 setSelectedCardINfo를 사용하도록 바꿈 
바꾸니까 정상 동작 합니다! 
https://github.com/user-attachments/assets/e1117c1f-bdcd-45af-965d-a06ca121d0f0
중점사항
=> [fix] 카드 선택시 화면에 동기화가 안되는 문제

backend/src/main/java/coffeeshout/global/config/DelayRemovalSchedulerConfig.java, backend/src/main/java/coffeeshout/global/interceptor/handler/postsend/ConnectPostSendHandler.java, backend/src/main/java/coffeeshout/global/interceptor/handler/postsend/DisconnectPostSendHandler.java, backend/src/main/java/coffeeshout/global/interceptor/handler/presend/ConnectPreSendHandler.java, backend/src/main/java/coffeeshout/global/interceptor/handler/presend/ErrorPreSendHandler.java, backend/src/main/java/coffeeshout/global/websocket/DelayedPlayerRemovalService.java, backend/src/test/java/coffeeshout/global/interceptor/CustomStompChannelInterceptorTest.java, backend/src/test/java/coffeeshout/global/interceptor/handler/postsend/DisconnectPostSendHandlerTest.java, backend/src/test/java/coffeeshout/global/interceptor/handler/presend/ConnectPreSendHandlerTest.java, backend/src/test/java/coffeeshout/global/websocket/DelayedPlayerRemovalServiceIntegrationTest.java, backend/src/test/java/coffeeshout/global/websocket/DelayedPlayerRemovalServiceTest.java, backend/src/test/java/coffeeshout/global/websocket/StompSessionManagerTest.java, backend/src/test/java/coffeeshout/websocket/WebSocketConnectionTest.java, backend/src/test/java/coffeeshout/websocket/WebSocketSimpleTest.java
- close #503 
1. TaskScheduler를 사용해서 player의 Disconnect 감지 시, 15초 뒤에 삭제되는 로직 구현했습니다.
1. 현재 DelayedPlayerRemovalServiceIntegrationTest에는 실제로 15초를 기다려야하는 테스트가 존재합니다.
우선 배포되었을 때 정상 작동하는지 보고 싶어서 지금은 이대로 올리지만, 정상 작동 확인이 되면 disable 처리하고 동일 로직을 검사하는 테스트를 CountdownLatch로 재구현해놓을게요~
=> [feat] player의 Disconnect 감지 시, 15초 뒤에 삭제되는 로직 구현

backend/src/main/java/coffeeshout/global/websocket/event/RoomStateUpdateEvent.java, backend/src/main/java/coffeeshout/global/websocket/event/RoomStateUpdateEventListener.java, backend/src/main/java/coffeeshout/room/domain/Room.java, backend/src/main/java/coffeeshout/room/domain/player/Players.java, backend/src/test/java/coffeeshout/room/domain/RoomTest.java
- close #526 
1. 호스트 퇴장 시, 남은 플레이어 중 랜덤으로 한 명 호스트로 승격하는 로직 구현
2. 자잘하게 RoomStateUpdateEvent도 recode로 변경했어요
중점사항
=> [feat] 호스트 퇴장 시, 남은 플레이어 중 랜덤으로 한 명 호스트로 승격하는 로직 구현

frontend/src/contexts/PlayerType/PlayerTypeContext.ts, frontend/src/contexts/PlayerType/PlayerTypeProvider.tsx, frontend/src/features/entry/pages/EntryMenuPage/EntryMenuPage.tsx, frontend/src/features/entry/pages/EntryNamePage/EntryNamePage.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx, frontend/src/features/room/order/components/MenuCount/MenuCount.tsx, frontend/src/features/room/order/components/PlayerMenu/PlayerMenu.tsx, frontend/src/features/room/order/pages/OrderPage.tsx
- close #550 
호스트가 방을 나가는 경우, 다른 게스트에게 자동으로 호스트 권한을 위임할 수 있도록 수정했습니다. https://github.com/woowacourse-teams/2025-coffee-shout/commit/2af9683f5af29bb61e980de070d09c9bd778870b
PlayerTypeContext에서 setPlayerType을 외부로 노출해, Lobby에서 플레이어 정보를 다시 불러올 때마다(즉, 다른 참여자가 방을 나갔다 들어오는 경우) 자신의 playerType을 갱신할 수 있도록 했습니다. 이를 통해 게스트에서 호스트로 권한이 승격되는 상황에서도 화면이 즉시 호스트용으로 렌더링되도록 보장했습니다.
MenuCount와 PlayerMenu 컴포넌트 내부에서 참여자 정보를 Context로 가져오도록 수정하였습니다. https://github.com/woowacourse-teams/2025-coffee-shout/commit/bf37fd23ae83e63cbf215894bc7148b551b0f538
Button 컴포넌트의 height 속성의 기본값이 'large'이기 때문에 불필요한 Props 전달 부분을 제거하였습니다. https://github.com/woowacourse-teams/2025-coffee-shout/commit/25e0d0f83c8ccd0fb9e677b02c5ba420d390fa47
=> [feat] 호스트가 방을 나갈 경우, 다른 게스트에게 자동으로 호스트 권한 위임

frontend/src/features/room/lobby/components/GuideModal/GuideContent/GuideContent.styled.ts
- close #482 
이미지 크기를 px으로 고정하지 않고, 부모 크기의 %로 차지하도록 수정해줬습니다.
중점사항
=> [fix] 특정 비율에서 서비스 설명 모달내용이 모달창을 뚫고 내려오는 문제 해결

frontend/src/assets/download-icon.svg, frontend/src/features/room/order/pages/OrderPage.tsx
- close #578
1. 이미지 저장 기능이 불필요하다고 판단해서 버튼을 삭제했습니다.
중점사항
=> [feat] 이미지 저장 버튼 삭제

frontend/src/App.tsx, frontend/src/apis/websocket/contexts/WebSocketProvider.tsx, frontend/src/apis/websocket/hooks/useBackgroundRedirect.ts, frontend/src/apis/websocket/hooks/useWebSocketReconnection.ts
- close #596 
현재는 백엔드에서 diconnect를 감지하는 경우 15초 동안 사용자 정보를 유지했다가 15초 이후에 돌아오는 경우에는 사용자가 백그라운드에서 포그라운드로 다시 돌아와도 재연결을 해주지 않는데요.
때문에 발생하는 문제가 있습니다. 
15초 이후에 백그라운드에서 포그라운드로 돌아올 경우, 해당 사용자의 정보가 끊겨서 더 이상 참여하고 있지 않은 방에 계속 머물러 있는 상태입니다. 이때 리디렉션을 해주기 위해 `useBackgroundRedirect` 훅을 만들었습니다.
useBackgroundRedirect 훅은 **웹소켓 연결 상태(isConnected)와 페이지 가시성(isVisible), 백그라운드 전 웹소켓 연결 상태(wasConnectedBeforeBackground)** 을 기반으로 동작합니다.
사용자가 백그라운드로 나갔다가 다시 돌아왔을 때, 현재 사용자가 여전히 participants 목록에 존재하는지 확인하고, 존재하지 않으면 홈(/)으로 리다이렉트합니다.
백그라운드에서 포그라운드로 돌아온 경우, 웹소켓 연결 상태와 무관하게 약간의 지연을 두어 참가자 정보(participants 변수)가 업데이트될 시간을 주도록 했는데요. 처음에는 아래와 같이 0.2초로 설정했는데, 사용자 체감상 좀 느린 것 같기도 하고 해서 아예 setTimeout 을 제거했습니다.
제거 해도 우선 동작은 잘 됩니다. 하지만, 혹시 모를 업데이트 시간을 위해서 지연 시간을 살려두는게 맞을까요?
```tsx
const timeoutId = setTimeout(() => { …
```
=> [fix] 백그라운드에서 포그라운드로 돌아올 때 사용자 정보 확인 및 리디렉션 처리

frontend/src/components/@common/Toast/Toast.styled.ts, frontend/src/features/entry/pages/EntryMenuPage/EntryMenuPage.tsx, frontend/src/features/entry/pages/EntryNamePage/EntryNamePage.tsx, frontend/src/features/room/lobby/components/ParticipantSection/ParticipantSection.tsx, frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #605 
1. 기존에 `alert`로 처리하던 로직에 `toast` 컴포넌트를 사용하도록 수정했습니다.
2. `Modal` 내부에서 처리하는 `alert`는 `Toast`로 변경하지 않았습니다. 추후 수정이 필요할 것 같습니다. 
중점사항
=> [feat] alert -> toast로 변경

frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #681
https://github.com/user-attachments/assets/40e67b63-caf8-4737-a7b9-66763e45bf65
1. 기존에는 `useLocation`으로 `state`를 받아오는 과정에서 넘겨받는 값이 없는 경우에 대한 에러 처리가 없었습니다. 따라서 `state`의 값이 없을 때 빈객체를 할당하도록 해주었습니다.
2. `navigate` 조건에도 `qrCodeUrl`이 없을 때, `main` 경로로 이동하도록 수정했습니다.
중점사항
=> [fix] 잘못된 경로로 lobby 페이지에 접근했을 때 에러 페이지 뜨는 이슈

frontend/src/main.tsx
기존에는 mode가 development 였어서 Sentry 초기 설정이 안돌아갔었음
지금은 mode를 제대로 설정해주니까 dev, prod 배포할 때도 모두 production mode 로 설정됨
이 과정에서 main.tsx 에서 조건문이 통과되어 `SENTRY_DSN`이 없다는 오류 발생
SENTRY_DSN -> DSN_KEY로 환경변수 이름 변경
=> [fix] SENTRY_DSN -> DSN_KEY로 변경

frontend/src/features/entry/pages/EntryMenuPage/EntryMenuPage.tsx
- close #704
메뉴 직접입력을 할때는 seletecMenu가 null이라서 아래 코드를 통과 못하는것 같더라고요 
```js
useEffect(() => {
if (joinCode && qrCodeUrl && selectedMenu  && isConnected) {
navigate(`/room/${joinCode}/lobby`);
}
}, [joinCode, qrCodeUrl, selectedMenu, customMenuName, isConnected, navigate]);
```
그래서 아래와 같이 수정했습니다. 잘 작동하는거 확인 했습니다~
```js
useEffect(() => {
if (joinCode && qrCodeUrl && (selectedMenu || customMenuName) && isConnected) {
navigate(`/room/${joinCode}/lobby`);
}
}, [joinCode, qrCodeUrl, selectedMenu, customMenuName, isConnected, navigate]);
```
중점사항
=> [fix] 메뉴 직접 입력시 로비로 넘어가지 않는 오류

frontend/src/apis/rest/apiRequest.ts, frontend/src/features/room/lobby/hooks/useParticipantValidation.ts, frontend/webpack.common.js
- close #693 
해당 이슈는, 웹소켓 재연결 때문에 발생하는 문제입니다.
기본적으로 저희 서비스는, 참여자가 15초 이내에 해당 방에 다시 돌아오지 않을 경우, 서버에서 해당 사용자를 방에서 삭제합니다.
그렇기 때문에 참여자는 15초 이후에 방에 들어왔을 때, 어떤 액션도 취할 수 없습니다. 이미 이 방에 존재하지 않는 사용자이기 때문입니다.
보통은 방에서 사라지면, 해당 방에 남아있는 참여자들에게 모두 participants 정보가 브로드캐스트 됩니다.
이때, 15초 이후에 참여한 사용자도 마찬가지로 방에 들어왔을 때 웹소켓이 재연결되면서 participants 정보를 다시 받게 됩니다. 이때, 현재 본인이 현재 방에 남아있는지를 확인할 수 있는데요, 15초 이후에 진입하면 그 사용자는 더이상 방에 존재하지 않으므로 홈으로 리디렉션하도록 처리해두었습니다.
하지만, 문제는 방이 사라졌을 때 입니다.
참여자가 1명이거나, 2명 이상에서도 모두 재현 가능합니다.
모든 참여자가 15초 이상 동안 어떠한 이유로 웹소켓이 끊긴 채 방에 참여하지 않고 있을 경우에는 방이 사라지게 됩니다.
방이 사라지면, 해당 방 자체가 서버에서 지워졌으므로 브로드캐스트를 해주지 않습니다. 애초에 STOMP 자체에 의해 웹소켓이 재연결 된다고 하더라도, LobbyPage에서 클라이언트는 서버에 send를 보내지만 응답은 오지 않습니다. 즉, LobbyPage에서 매번 갱신되어야 할 participants 정보가 갱신되지 않는 것입니다. 이렇게 participants 정보가 갱신되지 않게 되면, 클라이언트에서 관리하는 …
=> [fix] 웹소켓 끊김 시 방 생존 여부 상태를 활용한 로비 화면 분기 처리

frontend/src/components/@common/Toast/ToastContext.tsx
- close #652 
토스트의 위치 때문에 토글을 누를 수 없어서 사용자 입장에서 3초를 기다려야 하는 불편함이 있었습니다.
원래는 토스트의 위치를 조금 위로 올리려고 했습니다. 하지만, 여러 사람에게 피드백을 받아본 결과, 토글과 가로 폭이 맞지 않아서, 약간 어색하다는 평이 있었습니다.
문제 상황을 다시 보면서 근본적인 원인을 살펴보니, 토스트의 타이머가 조금 길게 설정되어 있다는 점을 발견했습니다.
그래서 타이머를 1.2초로 줄였구요, 그 결과 사용자가 토글을 누르기까지의 대기 시간이 확 줄어들어 사용성이 훨씬 개선되었습니다!
**타이머 3초 → 1.2초 줄이기**
https://github.com/user-attachments/assets/0195ca9f-9155-4de8-8791-580f95dc35f7
=> [chore] Toast 타이머 단축

frontend/src/features/entry/pages/EntryMenuPage/EntryMenuPage.styled.ts, frontend/src/features/entry/pages/EntryMenuPage/components/SelectCategory/SelectCategory.styled.ts, frontend/src/features/entry/pages/EntryMenuPage/components/SelectMenu/SelectMenu.styled.ts, frontend/src/features/entry/pages/EntryMenuPage/components/SelectMenu/SelectMenu.tsx
- close #735 
카테고리와 메뉴 선택화면에서 스크롤이 가능하도록 수정했습니다!
https://github.com/user-attachments/assets/78297e92-bedd-4d94-ba51-e973cb6f10a9
=> [fix] 카테고리와 메뉴 선택 화면에서 스크롤 안되는 현상

frontend/package.json, frontend/src/features/home/components/Splash/Splash.styled.ts, frontend/src/features/miniGame/cardGame/components/PrepareOverlay/PrepareOverlay.styled.ts, frontend/src/features/miniGame/cardGame/components/PrepareOverlay/PrepareOverlay.tsx, frontend/src/features/room/lobby/components/GuideModal/GuideModal.styled.ts, frontend/src/features/room/order/pages/OrderPage.styled.ts, frontend/src/features/room/order/pages/OrderPage.tsx, frontend/src/features/room/roulette/components/RoulettePlaySection/RoulettePlaySection.styled.ts, frontend/src/features/room/roulette/pages/RouletteResultPage/RouletteResultPage.styled.ts
- close #672 
성능 최적화 과정에서 Layout Shift가 발생하던 구간들을 확인하고 해결했습니다.
이번에 개선한 주요 구간은 총 5가지입니다.
커밋을 잘게 쪼개 놨는데요, 그냥 Files changed만 보면 조금 헷갈릴 수도 있어서, 커밋 로그를 보면서 확인해주시면 훨씬 이해하기 쉬울 것 같아요!
1. 게임 시작 시 Ready 상태 표시 (https://github.com/woowacourse-teams/2025-coffee-shout/pull/739/commits/034221012e7c8bb6226461070b4dfb520e27c46a, https://github.com/woowacourse-teams/2025-coffee-shout/pull/739/commits/cf0bce5ca06f8643fe6316808e4702083f89228d, https://github.com/woowacourse-teams/2025-coffee-shout/pull/739/commits/c24b71e77d96f774222816e78f0b3767883b9d60)
2. 당첨자 결과 화면 (https://github.com/woowacourse-teams/2025-coffee-shout/pull/739/commits/9d2273306ea4ec21c52672135dcc8cc2967efdc3, https://github.com/woowacourse-teams/2025-coffee-shout/pull/739/commits/9db2830ecaea6fa315b4626ba42806720a09f0c6, …
=> [perf] Layout Shift 제거

frontend/src/components/@composition/CafeCategoryCard/CafeCategoryCard.styled.ts
- close #818 
화면이 작을때 카테고리 각 아이템이 겹쳐보이는 현상이 있었습니다
CafeCategoryCard 에 min-height를 적용하여 겹치지 않게 했습니다
https://github.com/user-attachments/assets/72afa64b-ea8a-409a-b9b4-2cb93a9002a5
중점사항
=> [fix]  카테고리 아이템이 겹쳐서 보이는 현상

frontend/src/constants/joinCode.ts, frontend/src/features/entry/pages/EntryMenuPage/utils/roomApiHelpers.ts, frontend/src/features/home/components/EnterRoomModal/EnterRoomModal.tsx
- close #755 
초대 코드의 길이가 4를 넘지 않도록 하고
최근 입력한 내용이 숫자나 영문이 아니면 state를 업데이트하지 않는 방식으로 수정했습니다.
```tsx
if (
value.length > 4 ||
(value.length > 0 && !/^[A-Z0-9]$/.test(value[value.length - 1].toUpperCase()))
) {
return;
}
```
중점사항
=> [feat] 초대 코드 모달의 입력 제한 추가

frontend/src/components/@composition/PlayerCard/PlayerCard.styled.ts
- close #397 
- 텍스트에 적용되어 있는 `overflow: hidden` 속성 때문에 넘치는 부분이 짤리는 문제였습니다.
```css
h4 {
white-space: nowrap;
overflow: hidden; 
text-overflow: ellipsis;
}
```
- 글씨의 높이를 늘려서 숨겨지지 않도록 했습니다.
```css
line-height: 2;
```
중점사항
=> [fix] 영어 닉네임인 경우 밑에 짤리는 문제 해결
