.github/workflows/close-issue.yml, .github/workflows/frontend-ci.yml
- close #53 
1. 프론트엔드 CI 환경 테스트 주석 해제
2. issue 자동 닫힘 스크립트에 백엔드 브랜치 추가
없습니다.
=> [chore] CI 환경 파일 수정

frontend/.storybook/main.ts, frontend/src/components/@common/Description/Description.styled.ts, frontend/src/components/@common/Description/Description.tsx, frontend/src/components/@common/Headline1/Headline1.styled.ts, frontend/src/components/@common/Headline1/Headline1.tsx, frontend/src/components/@common/Headline2/Headline2.styled.ts, frontend/src/components/@common/Headline2/Headline2.tsx, frontend/src/components/@common/Headline3/Headline3.styled.ts, frontend/src/components/@common/Headline3/Headline3.tsx, frontend/src/components/@common/Headline4/Headline4.styled.ts, frontend/src/components/@common/Headline4/Headline4.tsx, frontend/src/components/@common/Paragraph/Paragraph.styled.ts, frontend/src/components/@common/Paragraph/Paragraph.tsx, frontend/src/constants/color.ts, frontend/src/constants/colorMap.ts, frontend/src/types/colorKey.ts, frontend/src/utils/makeColorMap.ts
- close #64 
1. text 관련 컴포넌트에 color 지정할 수 있게 수정 
중점사항
=> [refactor] text 관련 컴포넌트에 color 지정할 수 있게하기

frontend/src/components/@common/ProgressCounter/ProgressCounter.stories.tsx, frontend/src/components/@common/ProgressCounter/ProgressCounter.styled.ts, frontend/src/components/@common/ProgressCounter/ProgressCounter.tsx
- close #49 
`ProgressCounter` 컴포넌트 구현
없습니다.
=> [feat] ProgressCounter 컴포넌트 구현

frontend/src/pages/EntryMenuPage/EntryMenuPage.styled.ts, frontend/src/pages/EntryMenuPage/EntryMenuPage.tsx
- close #98 
SelectBox의 options의 경우에는 서버 데이터로 받아와야 하는 부분이기 때문에, 우선 스토리북에 있는 객체 그대로 가져와 사용해주었습니다.
=> [feat] EntryMenuPage 구현

frontend/src/pages/MiniGameResultPage/MiniGameResultPage.styled.ts, frontend/src/pages/MiniGameResultPage/MiniGameResultPage.tsx
- close #90 
1. 게임 결과 화면 UI를 구현했습니다.
[피그마 UI]
[현재 구현된 UI]
게임에 따라 UI가 변경될 가능성이 높아서 일단 레이아웃 껍데기만 구현했습니다.
=> [feat] MiniGameResultPage 구현

frontend/src/pages/MiniGamePlayPage/MiniGamePlayPage.styled.ts, frontend/src/pages/MiniGamePlayPage/MiniGamePlayPage.tsx
- close #91 
- MiniGamePlayPage UI 구현
- 타이머 10초 후 게임 결과 페이지로 이동
https://github.com/user-attachments/assets/1f63d1a9-6d31-4c89-a54d-4451d4b912be
TODO를 적어놨는데, 게임 기능 구조 자체가 아예 존재하지 않아서 어디까지 구현해놔야할지 모르겠네요.
해당 이슈에서 기본적인 틀이라도 다 구현하는 게 맞을까요? 아니면, 다른 이슈를 추가해서 따로 구현하는 게 맞을까요?
우선 페이지 병합이 급하다고 판단하여 올립니다!
타이머 관련된 PR은 따로 올렸으니 이에 관한 리뷰는 타이머 PR에서 해주시면 감사하겠습니다 🙇🏻‍♀️
=> [feat] MiniGamePlayPage 구현

frontend/src/pages/HomePage/EnterRoomModal/EnterRoomModal.styled.ts, frontend/src/pages/HomePage/EnterRoomModal/EnterRoomModal.tsx, frontend/src/pages/HomePage/HomePage.tsx
- close #128 
1. 방 참가하기 모달 UI를 구현하고 메인 페이지의 버튼을 클릭하면 띄우도록 했습니다.
https://github.com/user-attachments/assets/ed86899a-6c3c-4458-865c-2d7a6f3389da
해당 초대 코드가 유효한지 검증하는 로직은 백엔드와 초대 코드 규칙에 대해 논의한 후에 추가적으로 구현해야 할 것 같습니다.
없습니다.
=> [feat] 방 참가하기 모달 구현

frontend/src/pages/MiniGameResultPage/MiniGameResultPage.tsx
- close #138 
1. 룰렛 현황 보러가기 버튼을 누르면 이동하는 경로를 `/roulette`으로 수정했습니다.
없습니다.
=> refactor: 이동하는 경로 수정

frontend/src/components/@composition/RouletteWheel/RouletteWheel.styled.ts, frontend/src/pages/LobbyPage/RouletteSection/RouletteSection.styled.ts
=> [design]  lobby 페이지에서 룰렛 상단에 있는거 수정 

frontend/src/components/@common/GameActionButton/GameActionButton.styled.ts
- close #82 
클릭하면 줄어드는 애니메이션 추가 
중점사항
=> [refactor] GameActionButton에 애니메이션 추가

frontend/src/components/@common/SelectBox/SelectBox.styled.tsx, frontend/src/pages/EntryNamePage/EntryNamePage.tsx
- close #139 
1. EntryNamePage에 TopBar 추가
2. SelectBox에 가로 padding 제거
중점사항
=> [fix] EntryNamePage에 TopBar 추가

frontend/src/components/@common/BackButton/BackButton.tsx, frontend/src/components/@common/Button/Button.stories.tsx, frontend/src/components/@common/GameActionButton/GameActionButton.tsx, frontend/src/components/@common/IconButton/IconButton.stories.tsx, frontend/src/components/@common/Input/Input.tsx, frontend/src/components/@common/RoomActionButton/RoomActionButton.tsx, frontend/src/components/@composition/PlayerCard/PlayerCard.stories.tsx, frontend/src/components/@composition/PlayerCard/PlayerCard.tsx, frontend/src/components/@composition/RouletteWheel/RouletteWheel.tsx, frontend/src/features/miniGame/cardGame/components/CardBack/CardBack.tsx, frontend/src/features/miniGame/cardGame/components/CardFront/CardFront.tsx, frontend/src/features/ui/Modal/ModalHeader/ModalHeader.tsx, frontend/src/layouts/Layout.stories.tsx, frontend/src/pages/HomePage/HomePage.tsx, frontend/src/pages/HomePage/Splash/Splash.tsx, frontend/src/pages/LobbyPage/LobbyPage.tsx, frontend/src/pages/LobbyPage/RouletteSection/RouletteSection.tsx, frontend/src/pages/MiniGamePlayPage/MiniGamePlayPage.tsx, frontend/src/pages/OrderPage/OrderPage.tsx, frontend/src/pages/RoulettePage/RoulettePage.tsx, frontend/src/pages/RouletteResultPage/RouletteResultPage.tsx
=> [chore] fe/dev -> fe/prod 아이콘 테스트

.github/workflows/frontend-cd.yml
=> [chore] frontend-cd.yml에 env FE_PROD_PATH 경로 수정

frontend/src/pages/RoulettePage/RoulettePage.tsx
- close #185 
https://github.com/user-attachments/assets/950cb9bf-f5c7-4d09-aad8-9ff320b631c8
중점사항
=> [fix] 룰렛을 돌려도 룰렛 화면이 보이지 않는 문제 해결

.github/workflows/frontend-cd.yml
=> [chore] fe/dev -> fe/prod

frontend/src/features/room/lobby/components/RouletteSection/RouletteSection.tsx
- RouletteView 타입 통합
- 배포 테스트를 위함
=> [refactor] RouletteView 타입 통합

frontend/src/components/@common/Description/Description.tsx, frontend/src/components/@common/Headline1/Headline1.tsx, frontend/src/components/@common/Headline2/Headline2.tsx, frontend/src/components/@common/Headline3/Headline3.tsx, frontend/src/components/@common/Headline4/Headline4.tsx, frontend/src/components/@common/Paragraph/Paragraph.tsx
=> [chore] import 순서 변경

.github/workflows/frontend-cd.yml, frontend/src/components/@composition/SectionTitle/SectionTitle.tsx
=> [chore] CloudFront invalidation 경로 수정

.github/workflows/frontend-cd.yml, frontend/src/components/@composition/PlayerCard/PlayerCard.stories.tsx
=> [chore] CloudFront invalidation /*로 수정

frontend/.storybook/preview.tsx
=> [fix] storybook/preview 내부 import 오류

frontend/src/components/@common/Modal/Modal.styled.ts, frontend/src/components/@composition/ProbabilityList/ProbabilityList.styled.ts, frontend/src/features/miniGame/pages/MiniGameResultPage/MiniGameResultPage.styled.ts, frontend/src/features/room/lobby/components/MenuModifyModal/MenuModifyModal.styled.ts, frontend/src/features/room/lobby/components/MenuModifyModal/MenuModifyModal.tsx, frontend/src/features/room/lobby/components/ParticipantSection/ParticipantSection.styled.ts, frontend/src/features/room/lobby/components/ParticipantSection/ParticipantSection.tsx, frontend/src/features/room/order/pages/OrderPage.styled.ts, frontend/src/styles/global.css
- close #178 
1. 메뉴 수정 모달 UI를 구현했습니다.
https://github.com/user-attachments/assets/59114a9a-cb1e-4b58-8be7-73cf76dcade8
2. 모달 공통 컴포넌트에 적용되어 있던 `overflow: hidden;` 속성을 삭제했습니다. 
3. 스크롤바를 제거하는 속성을 `global`에서 적용하도록 수정했습니다.
중점사항
=> [feat] 커피 메뉴 수정 모달 구현

.github/workflows/be-delete-merged-branch.yml
- close #219 
1. dev 병합 시 자동 삭제
중점사항
=> [chore] dev 브랜치 병합 시 남아있는 브랜치 자동 삭제

frontend/src/components/@common/Button/Button.styled.ts, frontend/src/components/@common/Button/Button.tsx, frontend/src/features/miniGame/cardGame/components/CardBack/CardBack.styled.ts, frontend/src/features/miniGame/cardGame/components/CardBack/CardBack.tsx, frontend/src/features/miniGame/cardGame/components/CardFront/CardFront.styled.ts, frontend/src/features/miniGame/cardGame/components/CardFront/CardFront.tsx, frontend/src/types/styles.ts
- close #144 
- 'small' | 'medium' | 'large’ 타입 통일했습니다.
=> [refactor] 'small' | 'medium' | 'large’ 타입 통일

.github/workflows/fe-delete-merged-branch.yml
- close #221
1. 보호된 브랜치는 제거되지 않도록 설정
2. 병합 시 이전 브랜치 제거 후 pr 코멘트 남김
중점사항
로직 동작 방식 확인 후 문제 사항 토론 후 approve 바람
=> [chore] 프론트엔드 dev 병합 시 이전 브랜치 삭제 

backend/src/main/java/coffeeshout/room/application/RoomService.java, backend/src/main/java/coffeeshout/room/domain/service/RoomCommandService.java, backend/src/main/java/coffeeshout/room/domain/service/RoomQueryService.java, backend/src/main/java/coffeeshout/room/ui/RoomRestController.java, backend/src/test/java/coffeeshout/room/application/RoomServiceTest.java
- close #232 
1. joinCode 존재여부 
중점사항
=> [Feat] Room 존재 여부 확인 API 및 로직 추가

backend/src/main/java/coffeeshout/global/exception/WebSocketExceptionHandler.java, backend/src/main/java/coffeeshout/minigame/application/CardGameService.java, backend/src/main/java/coffeeshout/minigame/ui/response/MiniGameRanksMessage.java, backend/src/main/java/coffeeshout/minigame/ui/response/MiniGameScoresMessage.java, backend/src/main/java/coffeeshout/room/domain/Room.java, backend/src/main/java/coffeeshout/room/domain/player/Players.java, backend/src/main/java/coffeeshout/room/domain/roulette/ProbabilityCalculator.java, backend/src/test/java/coffeeshout/minigame/application/CardGameServiceTest.java, backend/src/test/java/coffeeshout/minigame/application/TestConfig.java, backend/src/test/java/coffeeshout/room/ui/RoomWebSocketControllerTest.java
- close #266 
1. 카드게임이 끝났을 때 등수와 함께 점수도 반환
- "/topic/room/{joinCode}/score"; -> 점수 반환
"/topic/room/{joinCode}/rank"; -> 등수 반환
중점사항
=> [feat] 카드게임이 끝났을 때 등수와 함께 점수도 반환

.github/workflows/frontend-ci.yml
=> fix : env 생성 경로 수정 후 배포 

.github/workflows/frontend-ci.yml, frontend/src/types/miniGame.ts
=> docs : 주석 제거

frontend/src/types/miniGame.ts
=> docs : 주석 수정

frontend/package-lock.json, frontend/package.json, frontend/src/apis/rest/apiRequest.ts, frontend/src/main.tsx, frontend/webpack.common.js
- close #355 
1. Sentry로 에러 트래킹 환경을 구축했습니다.
중점사항
=> [chore] fe 에러트래킹 환경 구축

backend/src/main/java/coffeeshout/global/config/MiniGameTaskSchedulerConfig.java, backend/src/main/java/coffeeshout/room/ui/RoomWebSocketController.java, backend/src/test/java/coffeeshout/room/ui/RoomWebSocketControllerTest.java
- close #379 
- 룰렛 결과 전송 경로를 `/topic/room/{joinCode}/roulette`에서 `/topic/room/{joinCode}/winner`로 변경
중점사항
=> [refactor] 당첨자 반환 구독 엔드포인트 수정

frontend/src/apis/rest/apiRequest.ts, frontend/src/apis/websocket/utils/getWebSocketUrl.ts
=> [chore] API URL을 HTTP -> HTTPS 로 변경

backend/src/main/java/coffeeshout/minigame/ui/response/MiniGameStateMessage.java
- close #391 
1. cardGame state에서 카드를 선택한 사용자의 colorIndex도 포함하도록 변경했습니다.
중점사항
=> [feat] cardGame state에서 카드를 선택한 사용자의 colorIndex도 포함

frontend/src/main.tsx
=> [refactor] Sentry 경로 https로 수정

frontend/src/main.tsx
=> Fe/dev -> Fe/prod

.github/workflows/backend-ci.yml, backend/src/main/java/coffeeshout/global/config/MiniGameTaskSchedulerConfig.java, backend/src/main/java/coffeeshout/global/config/WebSocketConfig.java, backend/src/main/java/coffeeshout/global/config/WebSocketSchedulerConfig.java, backend/src/main/java/coffeeshout/global/log/LogAspect.java, backend/src/main/java/coffeeshout/global/websocket/LoggingSimpMessagingTemplate.java, backend/src/main/java/coffeeshout/minigame/ui/response/MiniGameStateMessage.java, backend/src/main/java/coffeeshout/room/ui/RoomWebSocketController.java, backend/src/test/java/coffeeshout/room/ui/RoomWebSocketControllerTest.java
- close #이슈번호
1.
@Daeun-100 @sooyeoniya @rosielsh 
본 pr이 머지되면, 룰렛 돌려서 당첨자 뽑는 웹소켓 API 구독 경로가 아래처럼 바뀝니다.
`"/topic/room/{joinCode}/roulette"` -> `"/topic/room/{joinCode}/winner"`
=> [feat] prod 배포 (CI, heart beat, 엔드포인트, 로깅 수정)

backend/src/main/java/coffeeshout/room/domain/player/Players.java
- close #이슈번호
1. players 필드 `Collections.synchronizedList(new ArrayList<>())`로 변경
중점사항
=> [feat] Players 생성자에 동기화된 리스트 적용

frontend/src/features/room/roulette/pages/RoulettePlayPage/RoulettePlayPage.tsx
- close #411 
당첨자 구독 경로 winner로 수정하였습니다. 
수정후 전체 플로우 잘 돌아가는거 확인했습니다. 
중점사항
=> [refactor] 당첨자 구독 경로 winner로 수정

backend/src/main/java/coffeeshout/room/domain/Room.java, backend/src/test/java/coffeeshout/room/application/RoomServiceTest.java, backend/src/test/java/coffeeshout/room/domain/RoomTest.java
- close #413
1. 방 9명 초과 참가 시, 방이 ready 상태여야만 참여할 수 있다.
중점사항
=> [fix] 방 비즈니스 로직 예외 시 error 레벨로 변경

backend/src/test/java/coffeeshout/minigame/application/CardGameServiceRealTimeTest.java
- close #405 
1. 기존에 disabled된 테스트를 enabled하였습니다.
2. 테스트 시도 시 실패된 것을 해결하였습니다.
중점사항
=> [test] 통합 테스트 disabled 해제 및 테스트 실패 해결

frontend/package-lock.json, frontend/package.json, frontend/src/apis/rest/apiRequest.ts, frontend/src/apis/utils/reportSentryError.ts, frontend/src/apis/websocket/contexts/WebSocketProvider.tsx, frontend/webpack.common.js
=> [chore] Sentry 부분 prod에 반영

frontend/src/main.tsx
=> fix: Sentry DSN 키를 환경 변수에서 하드코딩 값으로 변경 (#430)

frontend/src/main.tsx
제발 되게 해주세요.. 일단 배포 환경에서 환경변수 오류가 너무 많아서, Sentry에 있는 모든 환경변수가 안되는 것 같아요.
그래서 일단 주석 추가합니다. 다음주에 환경변수 쪽 한 번에 다 해결해봅시다.
그때 환경변수 잘 인식하면 API 쪽까지 환경변수 전부다 원래대로 돌리면 될 것 같아요.
=> [chore] Sentry 초기화 코드 수정 및 환경변수 기본값 설정

frontend/src/main.tsx
=> [chore] Sentry 초기화 코드 수정 및 환경변수 기본값 설정 (#433)

frontend/src/apis/rest/apiRequest.ts, frontend/src/apis/websocket/utils/getWebSocketUrl.ts, frontend/src/main.tsx
=> [chore] 환경변수 API URL을 개발 서버로 변경

frontend/src/features/room/lobby/pages/LobbyPage.tsx
- close #438 
1. joinCode가 없을 때는 send 요청을 보내지 않도록 수정함
중점사항
=> [fix] 로비 페이지에서 새로고침 시 에러 뜨는 이슈

backend/src/main/java/coffeeshout/minigame/domain/cardgame/CardGame.java, backend/src/main/java/coffeeshout/minigame/domain/cardgame/CardGameState.java, backend/src/main/java/coffeeshout/minigame/domain/task/CardGameTaskType.java, backend/src/test/java/coffeeshout/minigame/application/CardGameServiceRealTimeTest.java, backend/src/test/java/coffeeshout/minigame/ui/CardGameIntegrationTest.java
- close #476
1. 카드게임 설명 상태를 추가했습니다.
2. 추가된 상태에 따른 테스트 수정
중점사항
=> [feat] 게임 설명 상태 추가

backend/src/main/java/coffeeshout/global/interceptor/CustomStompChannelInterceptor.java
- close #이슈번호
1. Long 파싱하는 방법 변경
중점사항
=> [fix] Long타입 파싱하는 법 변경

frontend/src/features/room/roulette/components/RoulettePlaySection/RoulettePlaySection.tsx
- close #463 
처음에는 아래 방식으로 구현했습니다
```js
{(Math.round(myProbabilityChange * 1000) / 1000).toFixed(2)}%
```
이 방법의 문제점!!
1. 어떤 역할을 하는지 명확히 알 수 없음
2. 수학적 계산과 UI 포맷팅이 한 줄에 혼재함
그래서 개선할 수 있는 방법을 찾아보다가 `Intl.NumberFormat`라는 것을 알게되었습니다
mdn문서 : Intl.NumberFormat 은 언어에 맞는 숫자 서식을 지원하는 객체의 생성자입니다.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
```js
// 소수점 2자리까지 표시하는 포맷터 (국제화 지원)
const formatPercent = new Intl.NumberFormat('ko-KR', {
minimumFractionDigits: 2,  // 최소 소수점 자릿수
maximumFractionDigits: 2,  // 최대 소수점 자릿수
});
```
개선 효과
1. 목적이 명확해지고 복잡한 수학 공식이 사라져 이해하기 쉬워짐
2. 관심사 분리 가능 
중점사항
=> [fix]  룰렛 페이지에서 당첨 확률 변화 무한한 소수점이 생기는 문제

backend/src/main/java/coffeeshout/global/websocket/event/RoomStateUpdateEventListener.java, backend/src/test/java/coffeeshout/global/interceptor/CustomStompChannelInterceptorTest.java, backend/src/test/java/coffeeshout/global/interceptor/handler/postsend/DisconnectPostSendHandlerTest.java
- close #522
1.  앱 전환시 제거된 플레이어, 룰렛에도 반영
중점사항
=> [feat] 앱 전환시 제거된 플레이어, 룰렛에도 반영

frontend/src/features/room/lobby/components/ParticipantSection/ParticipantSection.tsx
=> [fix] isReady가 undefined일 수있는 오류 해결 

frontend/src/contexts/CardGame/CardGameProvider.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx, frontend/src/features/miniGame/cardGame/pages/CardGameReadyPage.tsx, frontend/src/types/miniGame.ts
=> [refactor] description -> prepare로 수정

frontend/src/contexts/CardGame/CardGameProvider.tsx, frontend/src/features/miniGame/cardGame/pages/CardGamePlayPage.tsx, frontend/src/features/miniGame/cardGame/pages/CardGameReadyPage.tsx, frontend/src/types/miniGame.ts
=> refactor: prepare로 수정 (#539)

.github/workflows/frontend-ci.yml, frontend/buildspec.yml, frontend/src/apis/rest/apiRequest.ts, frontend/src/apis/websocket/utils/getWebSocketUrl.ts, frontend/src/main.tsx, frontend/webpack.common.js
1. 주석 처리 되어있는 환경변수 수정
2. buildspec에서 s3 업로드 및 CloudFront 무효화 부분 삭제 (권한 없어서 안됨)
=> [chore] 환경변수 수정

frontend/src/features/home/pages/HomePage.styled.ts
- close #591
https://github.com/user-attachments/assets/2dacf1a6-f75c-45f6-ba43-1c23db570d68
중점사항
=> [fix] 로고 이미지 반응형 처리 

backend/src/main/java/coffeeshout/room/ui/response/PlayerResponse.java
- close #645
1. PlayerMenuResponse에서 menuId는  사용하지 않기 때문에 지워버렸습니다~
중점사항
=> [fix] update-players DTO생성 과정에서 예외 발생하는 오류 수정

frontend/src/features/room/order/components/MenuCount/MenuCount.tsx, frontend/src/features/room/order/components/PlayerMenu/PlayerMenu.tsx
- close #635 
메뉴 이름  과 온도를 조합해 새로운 메뉴 key를 만들고 set에 저장해
같은 메뉴라도 HOT/ICE에 따라 다른 메뉴로 취급되게 변경하였습니다. 
중점사항
=> [refactor] 주문 목록 페이지에 hot/ice 정보 추가

frontend/src/components/@common/IconTextItem/IconTextItem.styled.ts, frontend/src/components/@common/IconTextItem/IconTextItem.tsx, frontend/src/components/@common/MenuListItem/MenuListItem.styled.ts, frontend/src/components/@common/MenuListItem/MenuListItem.tsx, frontend/src/features/room/lobby/components/JoinCodeModal/InvitationModal.tsx, frontend/src/features/room/lobby/components/TabBar/TabBar.styled.ts
- close #658 
- close #657
1. 모바일로 확인하니 글씨가 파랗게 보이는 부분들이 있었습니다. 따라서 텍스트에 `Paragraph` 컴포넌트를 적용해 주었습니다.
2. `TabBar` 글씨가 작게 보이는 문제를 해결하기 위해 16px로 고정해주었습니다.
중점사항
=> [design] 글씨 색상 파랗게 나오는 부분 수정

frontend/webpack.common.js
- close #695 
환경변수 추가할 때, dotenvEnv 를 추가하는 부분이 빠졌더라구요! 이 부분 때문에 발생하는 오류인 것 같아서 일단 추가해두었습니다.
dev에 올리고 제대로 동작하는지 확인해봐야할 것 같습니다.
=> [fix] 웹팩 환경변수 오류 수정

frontend/src/features/entry/pages/EntryMenuPage/utils/roomApiHelpers.ts
백엔드 쪽에서 joinCode를 4자리로 변경함에 따라, 프론트도 수정해주었습니다!
현재 dev에서 초대초드로 방 참가하기가 안돼서 바로 병합하는게 좋을 것 같아요!
=> [feat] joinCode 5 -> 4자리로 변경

frontend/src/styles/global.css
- close #817 
모바일에서 당겨서 새로고침되는 것을 막았습니다!
```css
/*당겨서 새로고침 막기*/
overscroll-behavior: none;
```
중점사항
=> [feat] 모바일에서 새로고침 막기 
